### PR TITLE
Adding inspection packages

### PR DESCRIPTION
**Pull request by ftomassetti**
This package provides routes to get basic statistics about the content of the repository.

At this time it exposes two routes: one to get all nodes by language and one to get all nodes by classifier.

My main doubt is around tests: I inserted tests in the tests package, but I am not sure if I should instead create a separate package for the tests that are specific for this package.

### CODE REVIEW

**Comment by ftomassetti** [comment]
Rebased after merging #15

**Comment by joswarmer** [comment]
I think that we should create a folder. per package under test/src.  That keeps the overall structure simple, and we are still able to see which tests are for which package.  This is similar to the way we are doing this in the lionweb-typescript package, and I like this consistency.
No problem keeping it as-is for now, but when it grows we should reorganise.

**Review by joswarmer — APPROVED** [review]
Looking good.

**Comment by ftomassetti** [comment]
Thank @joswarmer . I will then merge it, remove the branch and perhaps do the reorganization of tests with the next PR

**Pull request merged**
