### PR TITLE
Setup release-it

### LINKED ISSUE #36: Adding tags or release on NPM
When using the lionweb-repository, it would be convenient to be able to refer to a specific version.
It would be ideal to have versions of npm which we can use. Alternatively it would be useful to have tags indicating various versions, as we would clone the repository, checkout the tag and build that specific version.
Without npm version or tags, we use scripts that just clone the repository and use the most recent commit. But that mean that when APIs change, tests that used to pass now fail

### PR DESCRIPTION
**Pull request by ftomassetti**
Fix #36 

I configured release-it. I cannot _really_ test it without actually make a release.

I tried it in dry-run mode. You can see a [recording here](https://www.loom.com/share/109803951913427dbf85f1f3e7db1385).

Even in dry-run mode it created a tag (which I then deleted).

Note that I committed also package-lock.json because release-it would complain otherwise and because I think it should committed.

### CODE REVIEW

**Comment by joswarmer** [comment]
Hi, can’t take a look now, am traveling. Will be this weekend or next week

**Comment by ftomassetti** [comment]
Not urgent, it can wait. Thank you for the message

**Comment by joswarmer** [comment]
If the repository is released. how would you start the server from it?

**Comment by ftomassetti** [comment]
> Hard to test this as we cannot just do test releases :-(. 

Perhaps we can do some testing using a local npm repository. I will see if I am able to do that

> Looking at the package.json I see that only the top package is release, while all the "real" packages are not. Release-it does not automatically understand and release multiple packages in workspaces, so I guess it won't work as most code won't be released.

You are right. I thought I understood release-it supported multiple packages out of the box but I was wrong. I have now updated it following https://github.com/release-it/release-it/blob/main/docs/recipes/monorepo.md

**Comment by ftomassetti** [comment]
Unfortunately, running a local npm registry and having release-it work with it seems beyond my TS skills. I spent a few hours trying but did not make much progress. There are too many parts of the node-js ecosystem I am just ignorant about

**Comment by joswarmer** [comment]
Ok, I will try it, I have verdaccio as a local npm registry, hopefully it will work with release-it.

**Comment by ftomassetti** [comment]
> Can you explain what this means, I cannot find it in the release-it docs:
> 
> ```
>   "release-it": {
>       "git": false
>     }
> ```

I think I added it temporarily to avoid the system creating tags while I was playing with release-it

**Comment by joswarmer** [comment]
As it isn't working and I am not sure we still need this, should we close this PR?

**Pull request closed without merging**
